name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sentry Release
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: b62c53663f1e4d6f8586077fd010fcfe9a5d2b1fee664bfaa627616c49e4892e
          SENTRY_ORG: kang-ma
          SENTRY_PROJECT: nestjs_boilerplate
        with:
          environment: production