name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sentry Release
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: fbae131eb6ac4d8f919da1f8ef2fe74ba34e874142724e6e9587c9ce9399a844
          SENTRY_ORG: kang-ma
          SENTRY_PROJECT: nestjs_boilerplate
        with:
          environment: development